{"name": "test_export_as_cv[chromium]", "status": "broken", "statusDetails": {"message": "requests.exceptions.ReadTimeout: HTTPConnectionPool(host='10.99.13.11', port=80): Read timed out. (read timeout=10)", "trace": "E   TimeoutError: timed out\n\nThe above exception was the direct cause of the following exception:\nE   urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='10.99.13.11', port=80): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\nE   requests.exceptions.ReadTimeout: HTTPConnectionPool(host='10.99.13.11', port=80): Read timed out. (read timeout=10)"}, "parameters": [{"name": "browser_name", "value": "'chromium'"}], "start": 1749464398732, "stop": 1749464398732, "uuid": "8c12c19d-8f39-4c0c-8b5c-734d16c38893", "historyId": "1b69ac612c51d0ec1b3cde1f3bec2c96", "testCaseId": "ccf3f551eed0e6649f27722edf58f560", "fullName": "tests.Automation_tests.test_admin_playout#test_export_as_cv", "labels": [{"name": "feature", "value": "AdminPlayout"}, {"name": "parentSuite", "value": "tests.Automation_tests"}, {"name": "suite", "value": "test_admin_playout"}, {"name": "host", "value": "TR-GKJF6LPM4P"}, {"name": "thread", "value": "32008-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.Automation_tests.test_admin_playout"}]}