{"name": "test_clear_all_items_playout_history[chromium]", "status": "broken", "statusDetails": {"message": "requests.exceptions.ReadTimeout: HTTPConnectionPool(host='10.99.13.11', port=80): Read timed out. (read timeout=10)", "trace": "E   TimeoutError: timed out\n\nThe above exception was the direct cause of the following exception:\nE   urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='10.99.13.11', port=80): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\nE   requests.exceptions.ReadTimeout: HTTPConnectionPool(host='10.99.13.11', port=80): Read timed out. (read timeout=10)"}, "parameters": [{"name": "browser_name", "value": "'chromium'"}], "start": 1749464408759, "stop": 1749464408759, "uuid": "6587ff0c-45a0-4796-a529-ec00d6e42132", "historyId": "253ff02ae4f82bcd12998af8a41ad44a", "testCaseId": "ac2caa6bc9291d0c5ab192f2a5e9ab4a", "fullName": "tests.Automation_tests.test_admin_playout#test_clear_all_items_playout_history", "labels": [{"name": "feature", "value": "AdminPlayout"}, {"name": "parentSuite", "value": "tests.Automation_tests"}, {"name": "suite", "value": "test_admin_playout"}, {"name": "host", "value": "TR-GKJF6LPM4P"}, {"name": "thread", "value": "32008-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.Automation_tests.test_admin_playout"}]}