{"name": "test_distribution_history_clear_all[chromium]", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.189.200.6', port=80): Max retries exceeded with url: /api/v1/authenticate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113b33ad0>: Failed to establish a new connection: [Errno 51] Network is unreachable'))", "trace": "E   OSError: [Errno 51] Network is unreachable\n\nThe above exception was the direct cause of the following exception:\nE   urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x113b33ad0>: Failed to establish a new connection: [Errno 51] Network is unreachable\n\nThe above exception was the direct cause of the following exception:\nE   urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='10.189.200.6', port=80): Max retries exceeded with url: /api/v1/authenticate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113b33ad0>: Failed to establish a new connection: [Errno 51] Network is unreachable'))\n\nDuring handling of the above exception, another exception occurred:\nE   requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.189.200.6', port=80): Max retries exceeded with url: /api/v1/authenticate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113b33ad0>: Failed to establish a new connection: [Errno 51] Network is unreachable'))"}, "parameters": [{"name": "browser_name", "value": "'chromium'"}], "start": 1758887139781, "stop": 1758887139781, "uuid": "6e2c7ed9-0f81-4046-a04c-996064433160", "historyId": "a86cb04676ec645cfec5a2a89ced6b7f", "testCaseId": "6e45bd3941ac0df73148f451d1366198", "fullName": "tests.Automation_tests.test_history#test_distribution_history_clear_all", "labels": [{"name": "feature", "value": "History"}, {"name": "parentSuite", "value": "tests.Automation_tests"}, {"name": "suite", "value": "test_history"}, {"name": "host", "value": "TR-GKJF6LPM4P"}, {"name": "thread", "value": "62852-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.Automation_tests.test_history"}]}