{"name": "test_distribution_history_print[chromium]", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.189.200.6', port=80): Max retries exceeded with url: /api/v1/authenticate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113b037d0>: Failed to establish a new connection: [Errno 51] Network is unreachable'))", "trace": "E   OSError: [Errno 51] Network is unreachable\n\nThe above exception was the direct cause of the following exception:\nE   urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x113b037d0>: Failed to establish a new connection: [Errno 51] Network is unreachable\n\nThe above exception was the direct cause of the following exception:\nE   urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='10.189.200.6', port=80): Max retries exceeded with url: /api/v1/authenticate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113b037d0>: Failed to establish a new connection: [Errno 51] Network is unreachable'))\n\nDuring handling of the above exception, another exception occurred:\nE   requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.189.200.6', port=80): Max retries exceeded with url: /api/v1/authenticate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113b037d0>: Failed to establish a new connection: [Errno 51] Network is unreachable'))"}, "parameters": [{"name": "browser_name", "value": "'chromium'"}], "start": 1758887139756, "stop": 1758887139756, "uuid": "4073cd41-f58b-456c-b59d-3f9b0e79ce1c", "historyId": "0e053fe8f5366c8932547438ff885d66", "testCaseId": "a6563ee0814d2fafc809d18dd1bf8cc2", "fullName": "tests.Automation_tests.test_history#test_distribution_history_print", "labels": [{"name": "feature", "value": "History"}, {"name": "parentSuite", "value": "tests.Automation_tests"}, {"name": "suite", "value": "test_history"}, {"name": "host", "value": "TR-GKJF6LPM4P"}, {"name": "thread", "value": "62852-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.Automation_tests.test_history"}]}