{"name": "test_search_user[chromium]", "status": "broken", "statusDetails": {"message": "requests.exceptions.ReadTimeout: HTTPConnectionPool(host='10.99.13.11', port=80): Read timed out. (read timeout=10)", "trace": "E   TimeoutError: timed out\n\nThe above exception was the direct cause of the following exception:\nE   urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='10.99.13.11', port=80): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\nE   requests.exceptions.ReadTimeout: HTTPConnectionPool(host='10.99.13.11', port=80): Read timed out. (read timeout=10)"}, "parameters": [{"name": "browser_name", "value": "'chromium'"}], "start": 1754305286533, "stop": 1754305286533, "uuid": "a7fbf5e8-d159-4544-9631-1ee1849605fa", "historyId": "682fdbdcc55046ca56b6495f335ee964", "testCaseId": "79ff57147a2ee86e7559883a80fc8057", "fullName": "tests.Automation_tests.test_User_management#test_search_user", "labels": [{"name": "feature", "value": "UserManagement"}, {"name": "parentSuite", "value": "tests.Automation_tests"}, {"name": "suite", "value": "test_User_management"}, {"name": "host", "value": "TR-GKJF6LPM4P"}, {"name": "thread", "value": "83719-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.Automation_tests.test_User_management"}]}