INFO     root:test_VFD.py:168 FTP
INFO     root:test_VFD.py:168 FTPS
INFO     root:test_VFD.py:176 The server responded with an error. The operation was unsuccessful.
INFO     root:database.py:28 (58, '10.99.13.11', 'wneqa', 'nBhon2VaoHA8Fp8SpXnV+A==', 21, 0, '/wneclient/data/QA/ftp/files/testJakub', None, None, None, None, None, None, None, None, None, None, None, None, None, None, 0, 0, None, None, 0, None, 'tls', None, 'http', 0, None, 'tls', None, 'http', None, None, None, None, None)