{"name": "test_Check_Active_connection_with_Passive_Server[chromium]", "status": "broken", "statusDetails": {"message": "requests.exceptions.ReadTimeout: HTTPConnectionPool(host='10.189.200.4', port=80): Read timed out. (read timeout=10)", "trace": "E   TimeoutError: timed out\n\nThe above exception was the direct cause of the following exception:\nE   urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='10.189.200.4', port=80): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\nE   requests.exceptions.ReadTimeout: HTTPConnectionPool(host='10.189.200.4', port=80): Read timed out. (read timeout=10)"}, "parameters": [{"name": "browser_name", "value": "'chromium'"}], "start": 1757747153339, "stop": 1757747153339, "uuid": "5818de48-961e-4310-ad99-8dfff5f69c50", "historyId": "a1f892f021a0bc764c7a36293c3d21ae", "testCaseId": "7a7c042bf0d64a8f1e4cd9c7a108660c", "fullName": "tests.Automation_tests.test_VFD#test_Check_Active_connection_with_Passive_Server", "labels": [{"name": "feature", "value": "FD"}, {"name": "parentSuite", "value": "tests.Automation_tests"}, {"name": "suite", "value": "test_VFD"}, {"name": "host", "value": "TR-GKJF6LPM4P"}, {"name": "thread", "value": "94355-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.Automation_tests.test_VFD"}]}