{"uid":"4b4757e66a1912dae1a509f688f20b0f","name":"categories","children":[{"name":"Test defects","children":[{"name":"playwright._impl._errors.Error: Page.goto: net::ERR_INTERNET_DISCONNECTED at http://10.189.200.6/stories\nCall log:\nnavigating to \"http://10.189.200.6/stories\", waiting until \"load\"","children":[{"name":"test_distribution_history_exportascv[chromium]","uid":"5f05980aba4c09da","parentUid":"6d3a6e9e1424a65a4dda578e8fe4faab","status":"broken","time":{"start":1758886299281,"stop":1758887139657,"duration":840376},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":true,"retriesCount":0,"retriesStatusChange":false,"parameters":["'chromium'"],"tags":[]}],"uid":"6d3a6e9e1424a65a4dda578e8fe4faab"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.189.200.6', port=80): Max retries exceeded with url: /api/v1/authenticate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113b037d0>: Failed to establish a new connection: [Errno 51] Network is unreachable'))","children":[{"name":"test_distribution_history_print[chromium]","uid":"6d9801335bbe8b81","parentUid":"6ba2b049ea8555588549c339ca689d86","status":"broken","time":{"start":1758887139756,"stop":1758887139756,"duration":0},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":true,"retriesCount":0,"retriesStatusChange":false,"parameters":["'chromium'"],"tags":[]}],"uid":"6ba2b049ea8555588549c339ca689d86"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.189.200.6', port=80): Max retries exceeded with url: /api/v1/authenticate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1120c0a50>: Failed to establish a new connection: [Errno 51] Network is unreachable'))","children":[{"name":"test_playout_print[chromium]","uid":"91b28199d3bc2ec2","parentUid":"6ef3d92eba69cc456e8e5f29b71fd8e7","status":"broken","time":{"start":1758887139765,"stop":1758887139765,"duration":0},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":true,"retriesCount":0,"retriesStatusChange":false,"parameters":["'chromium'"],"tags":[]}],"uid":"6ef3d92eba69cc456e8e5f29b71fd8e7"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.189.200.6', port=80): Max retries exceeded with url: /api/v1/authenticate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113b33ad0>: Failed to establish a new connection: [Errno 51] Network is unreachable'))","children":[{"name":"test_distribution_history_clear_all[chromium]","uid":"801be0caf2dc39fc","parentUid":"2e2b5a67d787016f622b1fd516e6ede0","status":"broken","time":{"start":1758887139781,"stop":1758887139781,"duration":0},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":true,"retriesCount":0,"retriesStatusChange":false,"parameters":["'chromium'"],"tags":[]}],"uid":"2e2b5a67d787016f622b1fd516e6ede0"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.189.200.6', port=80): Max retries exceeded with url: /api/v1/authenticate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113b36610>: Failed to establish a new connection: [Errno 51] Network is unreachable'))","children":[{"name":"test_playout_export_as_cv[chromium]","uid":"1e75710b42188565","parentUid":"6d9e296f337bee0f29d06e6207ea9817","status":"broken","time":{"start":1758887139797,"stop":1758887139797,"duration":0},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":["'chromium'"],"tags":[]}],"uid":"6d9e296f337bee0f29d06e6207ea9817"}],"uid":"bdbf199525818fae7a8651db9eafe741"}]}