INFO     root:test_VFD.py:414 Validation from database
INFO     root:database.py:28 (16, 'AmBJrzbQ', '$2a$10$gPCRTaIwWS/WsjkrcMLZoeQlwFpVaJdCx4So1sY1Kaac.FHDLbJSW', None, None, 1, 1, 1, 1)
INFO     root:database.py:28 (16, '10.99.13.11', 'wneqa', 'nBhon2VaoHA8Fp8SpXnV+A==', 21, 0, '/wneclient/data/QA/ftp/files/testJakub', None, None, None, None, None, None, None, None, None, None, None, None, None, None, 0, 0, None, None, 0, None, 'tls', None, 'http', 0, None, 'tls', None, 'http', None, None, None, None, None)